<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class VendedoresSeeder extends Seeder
{
    public function run(): void
    {
        // Datos extraídos de tvendedor: [nick, apepat, apemat, nombres, dni]
        $vendedores = [
            ['EARCENTALES', 'ARCENTALES', 'ESPINOZA', 'ELDA', ''],
            ['RVERGARA', 'VERGARA', 'BROWN', 'ROXANA', ''],
            ['LMENDOZA', 'MENDOZA', 'VILLACORTA', 'LAHIT', ''],
            ['RCASTRO', 'CASTRO', 'A', 'ROXANA', ''],
            ['MSANCHEZ', 'SANCHEZ', 'GUERRA', 'MAYRA', ''],
            ['CMONCADA', 'MONCADA', 'A', 'CLEO', ''],
            ['PCOBOS', 'COBOS', 'A', 'PATRICIA', ''],
            ['AAREVALO', 'AREVALO', 'SINARAHUA', 'ANTONIO', ''],
            ['SOCAMPO', 'OCAMPO', 'LOPEZ', 'SUNNY MELYNA', ''],
            ['CKELITA', 'CAHUACHI', 'SOSA', 'KELITA', ''],
            ['CTORRES', 'TORRES', 'FLORIANO', 'MIGUELINA', ''],
            ['EHIDALGO', 'HIDALGO', 'GUTAPANA', 'ELIZABETH', ''],
            ['MTALEXIO', 'TALEXIO', 'A', 'MANUEL', ''],
            ['GCOBOS', 'COBOS', 'REYNA', 'GRECIA', ''],
            ['GREYNA', 'REYNA', 'BARTENS', 'GRETA MASIEL', ''],
            ['MCACERES', 'CACERES', 'PASTRANA', 'MARIA LUCIA', ''],
            ['EMARAPARA', 'MARAPARA', 'HUANIO', 'ENITH', ''],
            ['ATORRES', 'TORRES', 'APAGUEÑO', 'AMBAR ANAIS', ''],
            ['VYAHUARCANI', 'YAHUARCANI', 'A', 'VALERIA', ''],
            ['LZUMAETA', 'ZUMAETA', 'HUAYCAMA', 'VANESSA L', ''],
            ['AROMERO', 'ROMERO', 'CISNERO', 'ASTRID', ''],
            ['RAMABLE', 'AMABLE', 'DIAZ', 'ROSA INES', ''],
            ['EDIAZ', 'DIAZ', 'SOBRADO', 'EDITH ELIZABETH', ''],
            ['EPIÑA', 'PIÑA', 'GUERRA', 'EUNICE AMP', ''],
            ['MPEREZ', 'PEREZ', 'PAIMA', 'MAYTE S', ''],
            ['MDELAGUILA', 'DEL AGUILA', 'RUIZ', 'MARISELA', ''],
            ['FGUEVARA', 'GUEVARA', 'A', 'FRANCESCA', ''],
            ['MRODRIGUEZ', 'RODRIGUEZ', 'PAIMA', 'MANUELA C', ''],
            ['CFERREIRA', 'FERREIRA', 'IRUYARI', 'CINTYA', ''],
            ['NPINEDO', 'PINEDO', 'MARTINEZ', 'NAURIA', ''],
            ['LMANAMA', 'MANAMA', 'A', 'LISBET T', ''],
            ['ECORDOVA', 'CORDOVA', 'ANGULO', 'ELMA MARGARITA', ''],
            ['JGONGORA', 'GONGORA', 'A', 'JOHANA', ''],
            ['KCANAQUIRI', 'CANAQUIRI', 'ISUIZA', 'KELLY', ''],
            ['ICABANA', 'CABANA', 'A', 'INES', ''],
            ['LAMASIFUEN', 'AMASIFUEN', 'REATEGUI', 'LENY', ''],
            ['RZUCA', 'ZUCA', 'TOLEDO', 'RUTH', ''],
            ['ACURI', 'CURI', 'CUESPAN', 'ANY KAROL', ''],
            ['CNASHNATE', 'NASHNATE', 'FLORES', 'CINTHIA', ''],
            ['ESTEFANI', 'JARAMILLO', 'SORIA', 'ESTEFANI', '75809501'],
            ['KPANAIFO', 'PANAIFO', 'RAMIREZ', 'KARINA', ''],
            ['MDIAZ', 'DIAZ', 'MARIN', 'MAYRA', ''],
            ['RGUERRA', 'GUERRA', 'JIMENEZ', 'ROCIO', ''],
            ['MROJAS', 'ROJAS', 'PIZANGO', 'MIGUEL', ''],
            ['DYAHUARCANI', 'YAHUARCANI', 'CAHUAMARI', 'DORIS', ''],
            ['CSOLIS', 'SOLIS', 'UPIACHIHUA', 'CELESTE', ''],
            ['DSANGAMA', 'SANGAMA', 'MOZOMBITE', 'DANIA', ''],
            ['ECURMAYARI', 'CURMAYARI', 'CHOTA', 'ELIANA', ''],
            ['LSUCAPUCA', 'SUCAPUCA', 'A', 'LUZ', ''],
            ['IBEJARANO', 'BEJARANO', 'LOPEZ', 'IRMA J', ''],
            ['JNOTENO', 'NOTENO', 'MOZOMBITE', 'JACK IGOR', ''],
            ['DCAJIA', 'CAJIA', 'A', 'DANIA', ''],
            ['ALOPEZ', 'LOPEZ', 'PEÑA', 'ARNOLD', ''],
            ['CMACUYAMA', 'MACUYAMA', 'YASACAMA', 'CANDY', '48271670'],
            ['LIGLESIAS', 'IGLESIAS', 'MAYTAHUARI', 'LUZMILA', '05231020'],
            ['YA', 'YANELI', 'AVILA', 'TUESTA', ''],
            ['AYANELY', 'AVILA', 'TUESTA', 'YANELY', ''],
            ['VPAREDES', 'PAREDES', 'CASTRO', 'VERONICA', ''],
            ['MILPEQ', 'PEREZ', 'QUISPE', 'MILAGROS D', ''],
            ['OFICINA', 'OFICINA', 'OFICINA', 'OFICINA', ''],
            ['ESDIAZ', 'SHUPINGAHUA', 'DIAZ', 'ESTEFANI', ''],
            ['JCALAGUA', 'CALAGUA', 'ANGULO', 'JEAN CARLO', ''],
            ['JSANDOVAL', 'SANDOVAL', 'SILVA', 'MARIOLI JANET', '73748771'],
            ['LUMABO', 'MANUYAMA', 'BOSMEDIANO', 'LUZ', ''],
            ['YUVASI', 'VARASTEGUI', 'SILVA', 'YURI MERCEDES', ''],
            ['DBARDALES', 'BARDALES', 'TAPAYURI', 'DANIELA', ''],
            ['KEISVA', 'ISPARRAGA', 'VASQUEZ', 'KEVIN', ''],
            ['MJIMENEZ', 'JIMENEZ', 'NUÑEZ', 'MAX', '75446491'],
            ['PAREVALO', 'AREVALO', 'MURAYARI', 'PEDRO', ''],
            ['KROJAS', 'ROJAS', 'NASHNATE', 'KAROLAY', ''],
            ['RAYSITAR', 'GUEVARA', 'RIOS', 'RAYSA M', ''],
            ['HSORIA', 'SORIA', 'MENDOZA', 'HEINZ', ''],
            ['RFELICIDAD', 'REVILLA', 'ESCOBAR', 'FELICIDAD', ''],
            ['BRAMOS', 'RAMOS', 'MEJA', 'BRIGIDA', ''],
            ['JKOO', 'KOO', 'CORDOBA', 'JORGE ABEL', ''],
            ['CADRIANA', 'COLOMA', 'RENGIFO', 'ADRIANA', ''],
            ['IANDRADE', 'ANDRADE', 'AREVALO', 'IVONNE', ''],
            ['ETELLO', 'TELLO', 'NUÑEZ', 'ESTHER', ''],
            ['LINGA', 'INGA', 'SULLON', 'LIZ', ''],
            ['PIBONE', 'CHAVEZ', 'PAIMA', 'IBONE', ''],
            ['COCHAVANO', 'OCHAVANO', 'PANAIFO', 'CARMEN', ''],
            ['NORMAMANI', 'MAMANI', 'LOPEZ', 'NORMA YESENIA', ''],
            ['RUTHDEZA', 'DEZA', 'JIMENEZ', 'RUTH', ''],
            ['FLORBARDA', 'BARDALES', 'PACAYA', 'FLOR DE MARIA', ''],
            ['JLAZO', 'LAZO', 'ACHING', 'JOSE F', ''],
            ['MCURINUQUI', 'MARIA', 'CURINUQUI', 'PEREZ', ''],
            ['PMACEDO', 'PATRICIA', 'MACEDO', 'RUIZ', ''],
            ['LMORENO', 'MORENO', 'PIÑA', 'LUIS MIGUEL', ''],
            ['VCAHUAZA', 'CAHUAZA', 'PEÑA', 'VALERIA', ''],
            ['CALARCON', 'ALARCON', 'CAVALCANTE', 'CECILIA', ''],
            ['FIOVASQUEZ', 'VASQUEZ', 'ZAMBRANO', 'FIORELLA', ''],
            ['MMOZOMBITE', 'MOZOMBITE', 'NAVARRO', 'MAGVIS', ''],
            ['MIMACUYAMA', 'MACUYAMA', 'AHUANARI', 'BERTHA M', ''],
            ['MOVASNA', 'VASQUEZ', 'NAVARRO', 'MORELIA M', ''],
            ['XIVARGAS', 'VARGAS', 'LOPEZ', 'XIOMY', ''],
            ['MESTHER', 'MALAFAYA', 'HUAYAMBA', 'ESTHER', ''],
            ['EREATEGUI', 'REATEGUI', 'VASQUEZ', 'ERIKA JOHANA', ''],
            ['DILIA', 'WENINGER', 'GARCIA', 'DILIA', ''],
            ['BETHALVAN', 'ALVAN', 'MANIHUARI', 'BETHSABE', ''],
            ['FIOVARGAS', 'VARGAS', 'MOZOMBITE', 'DAMARIS FIORELLA', ''],
            ['ACHILICAHUA', 'CHILICAHUA', 'CASIMIRO', 'ANTONIA', ''],
            ['JVILLACORTA', 'VILLACORTA', 'HURINUQI', 'JUNIOR', '75105134'],
            ['KVALLES', 'VALLES', 'UPIACHIHUA', 'KAREN PATRICIA', ''],
            ['ATICONA', 'TICONA', 'HUAYTA', 'ANANELIA', ''],
            ['JTORREA', 'TORREALVA', 'ARREGUI', 'ROSARIO', ''],
            ['EDOMINGUEZ', 'DOMINGUEZ', 'AHUANARI', 'ESTELA', ''],
            ['ASANTANA', 'SANTANA', 'PACAYA', 'ADRIANA', ''],
            ['FIOCACHIQUE', 'CACHIQUE', 'REATEGUI', 'GREYSI FIORELLA', ''],
            ['YENY', 'MACHACA', 'CONDORI', 'YENY', ''],
            ['SSHIRLEY', 'SANCHEZ', 'HUANCA', 'SHIRLEY VIOLETA', ''],
            ['CJIMENA', 'CARCAUSTO', 'PUMA', 'JIMENA', ''],
            ['ELMERB', 'BAZAN', 'RENGIFO', 'ELMER', ''],
            ['NORALUZ', 'MULLISACA', 'AYARQUISPE', 'NORA LUZ', ''],
            ['JCARLOS', 'MUÑOZ', 'AGUINDA', 'CARLOS', ''],
            ['JEAPAZA', 'APAZA', 'JARA', 'JESICA', ''],
            ['EDQUISPE', 'QUISPE', 'VILCA', 'EDIHT AIDA', ''],
            ['RUSCALLE', 'CALLE', 'PHOCCO', 'RUSBI ALEXANDRA', ''],
            ['KMURAYARI', 'MURAYARI', 'IJUMA', 'KAREN', ''],
            ['CLLERENA', 'LLERENA', 'VILCHEZ', 'CHERRY', ''],
            ['RCABRERA', 'CABRERA', 'MELENDEZ', 'RUBI DANIELA', ''],
            ['JGONZALES', 'GONZALES', 'GUERRA', 'JHOANA PATRICIA', ''],
            ['ESTEBANS', 'SAHUARICO', 'MANIHUARI', 'ESTEBAN', ''],
            ['RCOBOS', 'COBOS', 'PIZANGO', 'RUBIEL', ''],
            ['MPASHANASTE', 'PASHANASTE', 'MAITAHUARI', 'MILAGROS', ''],
            ['BRODRIGUEZ', 'RODRIGUEZ', 'SALDAÑA', 'BRENDI', ''],
            ['BETSIOCHOA', 'OCHOA', 'MENDEZ', 'BETSI MARIVEL', ''],
            ['APEZO', 'LINARES', 'PEZO', 'ALMENDRA', ''],
            ['APINEDO', 'PINEDO', 'CABUDIVO', 'ALEJANDRA', ''],
            ['HMILAGROS', 'HUAMAN', 'CHOQUEPATA', 'MILAGROS', ''],
            ['JRVILLACORTA', 'VILLACORTA', 'CURINUQUI', 'JOSE LUIS', ''],
            ['SUCHARPEN', 'CHARPENTIER', 'SANDI', 'SUSANA', ''],
            ['EHUAYTA', 'HUAYTA', 'TICONA', 'ELENA', ''],
            ['BFABRCIO', 'BOCANEGRA', 'TORRES', 'FABRICIO', ''],
            ['FMAMANI', 'MAMANI', 'SUCARI', 'FLOR', ''],
            ['TMAMANI', 'MAMANI', 'CUEVA', 'MARY THALIA', ''],
            ['LFUENTES', 'FUENTES', 'TICONA', 'LINDA MARICIELO', ''],
            ['MILAGROSMT', 'MAMANI', 'TURPO', 'MILAGROS', '73352503'],
            ['IRENE123', 'HUACOTO', 'PARIAPAZA', 'IRENE', ''],
            ['CHGARCIA', 'GARCIA', 'RAMOS', 'CHANEL', ''],
            ['ANAPEREZ', 'PEREZ', 'LARREA', 'ANA', '75706927'],
            ['DMAYRA', 'DIAZ', 'MARIN', 'MAYRA IBETH', ''],
            ['RGREYSI', 'RAMIREZ', 'ARIMUYA', 'GREYSI', ''],
            ['CVERONICA', 'CONDORI', 'MOROCCO', 'VERONICA', ''],
            ['DELAGUILA', 'DEL AGUILA', 'GARCIA', 'KAREN', ''],
            ['AZUMAETA', 'ZUMAETA', 'PALLA', 'ARELIX', ''],
            ['AGUEDES', 'GUEDES', 'ZAMBRANO', 'AMILUZ', ''],
            ['ZCHARAJA', 'CHARAJA', 'CORNEJO', 'ZENAYDA', ''],
            ['MCURASI', 'CURASI', 'CUTIPA', 'MERY', ''],
            ['ALEYDE', 'APAZA', 'ROJAS', 'LEYDE RAQUEL', ''],
            ['MYIUGIA', 'MACHACA', 'CONDORI', 'YIURGIA', ''],
            ['HROXANA', 'HALLASI', 'YUPA', 'ROXANA', ''],
            ['FLORALEXIA', 'MAMANI', 'MAMANI', 'FLOR ALEXIA', ''],
            ['YQUISPE', 'QUISPE', 'TRUJILLO', 'ROSA YANETH', ''],
            ['EMASCO', 'MASCO', 'VILCA', 'ELIZABETH ESMERALDA', ''],
            ['SGARCIA', 'GARCIA', 'PAIMA', 'SELVA', '48762207'],
            ['DRICOPA', 'RICOPA', 'GONZALES', 'JUAN DANIEL', ''],
            ['SMALAFAYA', 'ANDRADE', 'MALAFAYA', 'SALVI ESTEFANI', ''],
            ['ATIHUAY', 'TIHUAY', 'TAPULLIMA', 'ALEJANDRINA', ''],
            ['MTAPAYURI', 'YPUSHIMA', 'TAPAYURI', 'MARCY CAROL', ''],
            ['ACHONG', 'ACHONG', 'CASEMIRO', 'CESIA ORELLY', ''],
            ['CVILLACORTA', 'ECHEVARRIA', 'VILLACORTA', 'COLETH AMPARO', ''],
            ['RAMANQUI', 'AYAMAMANI', 'AMANQUI', 'RUTH CELENIA', ''],
            ['RPEREZ', 'PEREZ', 'PAZ', 'RAUL', ''],
            ['GPANAIFO', 'PANAIFO', 'MURAYARI', 'GREYSI', ''],
            ['RBARBARAN', 'PINO', 'BARBARAN', 'ROSA MARIA', ''],
            ['KELITA', 'SOSA', 'CAHUACHI', 'KELITA', ''],
            ['VPANDURO', 'PANDURO', 'RIOS', 'VALERIEN DEL CARMEN', ''],
            ['ACRISTINA', 'ANDRADE', 'OLORTEQUI', 'KATERIN CRISTINA', ''],
            ['ISAAC', 'SANGAMA', 'AMASIFUEN', 'PERCY ISAAC', ''],
            ['YCACERES', 'CACERES', 'CAYO', 'YIAMIL', ''],
            ['GEO', 'PINEDA', 'JIHUALLANCCA', 'GEOVANNA', ''],
            ['DINA', 'BOCANEGRA', 'CORDOVA', 'DINA', '72899424'],
            ['MARJORIE', 'SOPLIN', 'VILCHEZ', 'MARJORIE', '76655740'],
            ['JOSE', 'AYACHI', 'CEGUA', 'JOSE ARMANDO', '72198858'],
            ['CARLOSV', 'CORDERO', 'TAMANI', 'VICTOR CARLOS', '75281184'],
            ['YESSICA', 'MAMANI', 'HUARACHA', 'YESSICA', '73581125'],
            ['CRISTAL', 'VERGARA', 'SANGAMA', 'CRISTAL', '72161398'],
            ['EDWIN', 'REATEGUI', 'MAHUA', 'EDWIN', '77082752'],
            ['AARCENTALES', 'PEREIRA', 'ARCENTALES', 'ANGEL CHRISTIAN', '70368475'],
            ['PSAJAMI', 'PAULO', 'SAJAMI', 'ARIMUYA', ''],
            ['CSAMANTA', 'CABUDIVO', 'CASIMIRO', 'SAMANTA', '74841354'],
            ['EPAMELA', 'CCOA', 'PARI', 'ESTEFANI PAMELA', ''],
            ['MLISBETH', 'MAMANI', 'VILCA', 'LISBETH', ''],
            ['GDEISY', 'CONDORI', 'COLQUEHUANCA', 'GILDA DEISY', ''],
            ['MJANETH', 'MAMANI', 'LUQUE', 'JANETH', ''],
            ['GANDREA', 'GUILLEN', 'RODRIGUEZ', 'ANDREA', ''],
            ['OSAMELI', 'OJANAMA', 'TORRES', 'SAMELI', ''],
            ['LEYDI', 'CACERES', 'CAYO', 'LEYDI', ''],
            ['YPINEDO', 'PINEDO', 'APAGUEÑO', 'YASIRA', ''],
            ['SIGNASIO', 'SHUÑA', 'RODRIGUEZ', 'IGNACIO', ''],
            ['GCARPIO', 'CARPIO', 'CANAYO', 'GINA', ''],
            ['NICOL', 'OROCHE', 'RUIZ', 'NICOL', ''],
            ['CLAUDIA', 'SILVANO', 'TAMANI', 'CLAUDIA', ''],
            ['RAQUEL', 'APAZA', 'ROJAS', 'RAQUEL', '47616374'],
            ['QNATI', 'QUISPE', 'TORRES', 'NATI', '42358513'],
            ['RSACSI', 'SACSI', 'SACSI', 'ROSA MARIA', '63284147'],
            ['GUILLEN', 'GUILLEN', 'VARGAS', 'GRECIA', '77755562'],
            ['DAMARIS', 'PILCO', 'SUCACAHUA', 'DAMARIS', '77200847'],
            ['ANA', 'MACEDO', 'GUERRA', 'ANA MARIA', '45721881'],
            ['ELIANA', 'MAMANI', 'MAMANI', 'NELY ELIANA', '73430287'],
            ['ECHAVEZ', 'CHAVEZ', 'GUERRA', 'EVOLI', ''],
            ['CCAMILA', 'CONDORI', 'PROVINCIA', 'LUISA CAMILA', ''],
            ['MARIA', 'AHPANCHO', 'CUELLAR', 'MARIA EUGENIA', '46326164'],
            ['GINA', 'MARAPARA', 'ISUIZA', 'GINA KEILA', ''],
            ['HCARRANZA', 'CARRANZA', 'ARIRAMA', 'HOMER', ''],
            ['ALMENDRA', 'TORRES', 'MARAPARA', 'GRACIA ALMENDRA', '75590913'],
            ['ROSA', 'COQUINCHE', 'COQUINCHE', 'ROSA', ''],
            ['FVIVIANA', 'NASHNATE', 'FLORES', 'VIVIANA', ''],
            ['PGLORIA', 'PEÑA', 'PUA', 'GLORIA DEL CARMEN', ''],
            ['RJHON', 'RENGIFO', 'ARIRAMA', 'JHON WILLY', ''],
            ['CHISTAMA', 'CHISTAMA', 'ARIRAMA', 'JENNIFER', ''],
            ['MSALCEDO', 'SALCEDO', 'CCANA', 'MEDALIT', '47697764'],
            ['VALLES', 'VALLES', 'UPIACHIHUA', 'KAREN', ''],
        ];

        $password = Hash::make('123456');
        $now = now();
        $usernamesUsados = [];

        DB::statement('SET FOREIGN_KEY_CHECKS=0');

        foreach ($vendedores as $v) {
            [$nick, $apepat, $apemat, $nombres, $dni] = $v;

            $username = strtolower($nick);
            $email    = strtolower($nick) . '@mundofantasia.com';
            $dni      = ($dni === '') ? '00000000' : $dni;

            // Evitar duplicados si el seeder se corre más de una vez
            if (DB::table('users')->where('username', $username)->exists()) {
                continue;
            }

            $idPersona = DB::table('persona')->insertGetId([
                'id_empresa'                => 1,
                'persona_nombre'            => $nombres,
                'persona_apellido_paterno'  => $apepat,
                'persona_apellido_materno'  => $apemat,
                'persona_email'             => $email,
                'persona_dni'               => $dni,
                'persona_tipo_documento'    => '1',
                'persona_blacklist'         => 'NO',
                'persona_empleado'          => 1,
                'person_codigo'             => uniqid('vend_', true),
                'persona_estado'            => 1,
                'created_at'                => $now,
                'updated_at'                => $now,
            ]);

            $idUser = DB::table('users')->insertGetId([
                'nombre_users'    => $nombres,
                'email'           => $email,
                'password'        => $password,
                'username'        => $username,
                'user_fotografia' => 'sin-fotografia.png',
                'id_persona'      => $idPersona,
                'users_estado'    => 1,
                'created_at'      => $now,
                'updated_at'      => $now,
            ]);

            // Rol Ventas (id = 5)
            DB::table('model_has_roles')->insert([
                'role_id'    => 5,
                'model_type' => 'App\\Models\\User',
                'model_id'   => $idUser,
            ]);

            // Tienda principal (id = 10)
            DB::table('user_tienda')->insert([
                'id_users'   => $idUser,
                'id_tienda'  => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
}
